board/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/update/', views.update, name='update'),
]

board/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)

    context = {
        'article': article,
    }
    return render(request, 'detail.html', context)

def new(request):
    return render(request, 'new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article()
    article.title = title
    article.content = content
    article.save()

    # {% url 'articles:index' %}
    return redirect('articles:detail', id=article.id)

def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()

    return redirect('articles:index')

def edit(request, id):
    article = Article.objects.get(id=id)
    context ={
        'article': article,
    }
    return render(request, 'edit.html', context)

def update(request, id):
    # 새로운 정보
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 기존정보
    article = Article.objects.get(id=id)

    article.title = title
    article.content = content
    article.save()

    return redirect('articles:detail', id=article.id)

board/articles/templates/detail.html
{% extends 'base.html' %}

{% block body%}
    <div class="card mt-3">
        <div class="card-header">
            {{ article.title }}
        </div>
        <div class="card-body">
            {{ article.content }}
        </div>
        <div class="card-footer">
            <p>{{ article.created_at}}</p>
            <a href="{% url 'articles:edit' id=article.id %}" class="btn btn-warning">edit</a>
            <a href="{% url 'articles:delete' id=article.id %}" class="btn btn-danger">delete</a>
        </div>

    </div>
{% endblock%}

board/articles/templates/edit.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:update' id=article.id%}" class="mt-4" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{article.title}}">

        </div>
        <div class="mb-3">
            <label for="content" class="form-label">content</label>
            <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{article.content}}</textarea>

        </div>

        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}

board/articles/templates/index.html
{% extends 'base.html' %}

{% block body%}
    
    <table class='table'>
        <thead>
            <tr>
                <th>#</th>
                <th>title</th>
                <th>link</th>
            </tr>

        </thead>
        <tbody>
            {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>
                    <a href="{% url 'articles:detail' id=article.id %}">detail</a>
                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>

{% endblock%}

board/articles/templates/new.html
{% extends 'base.html' %}

{% block body %}
    <form action="{% url 'articles:create' %}" class="mt-4" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">title</label>
            <input type="text" class="form-control" id="title" name="title">

        </div>
        <div class="mb-3">
            <label for="content" class="form-label">content</label>
            <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>

        </div>

        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}